import { Client } from "@gradio/client";
import type { VideoProvider, VideoRequest, GenerationResult } from "./types.js";

const SPACE_ID = process.env.HF_SPACE_ID ?? "multimodalart/self-forcing";
const ENDPOINTS = [
  process.env.HF_ENDPOINT?.trim(),
  "/video_generation_handler_example",
  "/video_generation_handler"
].filter(Boolean) as string[];

type ApiInfo = {
  named_endpoints?: Record<string, { parameters?: unknown[] }>;
};

function isFileLike(value: unknown): value is {
  url?: string;
  path?: string;
  name?: string;
  orig_name?: string;
  mime_type?: string;
} {
  return !!value && typeof value === "object" && (
    "url" in value || "path" in value || "name" in value || "orig_name" in value
  );
}

async function toBuffer(value: unknown): Promise<{ buffer: Uint8Array; filename: string; mimeType?: string } | null> {
  if (value instanceof Uint8Array) {
    return { buffer: value, filename: "aivideotop.mp4", mimeType: "video/mp4" };
  }

  if (typeof value === "string" && (value.startsWith("http://") || value.startsWith("https://"))) {
    const r = await fetch(value);
    if (!r.ok) throw new Error(`Failed to fetch generated media: ${r.status}`);
    return {
      buffer: new Uint8Array(await r.arrayBuffer()),
      filename: "aivideotop.mp4",
      mimeType: r.headers.get("content-type") ?? "video/mp4"
    };
  }

  if (!isFileLike(value)) return null;

  const url = value.url ?? value.path;
  if (!url) return null;

  const absolute = (url.startsWith("http://") || url.startsWith("https://"))
    ? url
    : `https://${SPACE_ID.replace("/", "-")}.hf.space${url.startsWith("/") ? url : `/${url}`}`;

  const r = await fetch(absolute);
  if (!r.ok) throw new Error(`Failed to fetch generated media: ${r.status}`);

  return {
    buffer: new Uint8Array(await r.arrayBuffer()),
    filename: value.orig_name ?? value.name ?? "aivideotop.mp4",
    mimeType: value.mime_type ?? r.headers.get("content-type") ?? "video/mp4"
  };
}

async function findMedia(data: unknown): Promise<{ buffer: Uint8Array; filename: string; mimeType?: string } | null> {
  if (Array.isArray(data)) {
    for (const item of data) {
      const found = await findMedia(item);
      if (found) return found;
    }
    return null;
  }

  const direct = await toBuffer(data);
  if (direct) return direct;

  if (data && typeof data === "object") {
    for (const value of Object.values(data as Record<string, unknown>)) {
      const found = await findMedia(value);
      if (found) return found;
    }
  }

  return null;
}

export class HuggingFaceProvider implements VideoProvider {
  private clientPromise: ReturnType<typeof Client.connect>;

  constructor() {
    const token = process.env.HF_TOKEN?.trim();
    this.clientPromise = Client.connect(SPACE_ID, token ? { token } : undefined);
  }

  async diagnose() {
    const client = await this.clientPromise;
    const info = await client.view_api() as ApiInfo;
    return Object.entries(info.named_endpoints ?? {}).map(([name, endpoint]) => ({
      name,
      parameters: endpoint.parameters?.length ?? 0
    }));
  }

  async generateVideo(input: VideoRequest): Promise<GenerationResult> {
    const client = await this.clientPromise;

    // Self-Forcing is a free Wan 2.1 T2V 1.3B ZeroGPU Space.
    // It exposes a final-video function as a normal Gradio endpoint.
    const seed = -1;
    const fps = 15;
    let lastError: unknown;

    for (const endpoint of ENDPOINTS) {
      try {
        console.log(`[hf] trying ${SPACE_ID}${endpoint}`);
        const result = await client.predict(endpoint, [input.prompt, seed, fps]);
        const media = await findMedia(result.data);
        if (media) {
          return {
            status: "completed",
            buffer: media.buffer,
            filename: media.filename,
            mimeType: media.mimeType,
            message: "Generated by Wan 2.1 Self-Forcing on Hugging Face ZeroGPU"
          };
        }
        lastError = new Error(`Endpoint ${endpoint} returned no video file`);
      } catch (error) {
        lastError = error;
        console.error(`[hf] endpoint ${endpoint} failed:`, error);
      }
    }

    throw new Error(
      `Hugging Face Self-Forcing generation failed: ${lastError instanceof Error ? lastError.message : String(lastError)}`
    );
  }
}
