import { Client } from "@gradio/client";
import type { VideoProvider, VideoRequest, GenerationResult } from "./types.js";

const SPACE_ID = "multimodalart/self-forcing";
const ENDPOINT = process.env.HF_ENDPOINT?.trim() || "/video_generation_handler_example";

type ApiInfo = {
  named_endpoints?: Record<string, { parameters?: unknown[] }>;
};

function isFileLike(value: unknown): value is {
  url?: string;
  path?: string;
  name?: string;
  orig_name?: string;
  mime_type?: string;
} {
  return !!value && typeof value === "object" && (
    "url" in value || "path" in value || "name" in value || "orig_name" in value
  );
}

function absoluteFileUrl(url: string) {
  if (url.startsWith("http://") || url.startsWith("https://")) return url;
  return `https://${SPACE_ID.replace("/", "-")}.hf.space${url.startsWith("/") ? url : `/${url}`}`;
}

async function toBuffer(value: unknown): Promise<{ buffer: Uint8Array; filename: string; mimeType?: string } | null> {
  if (value instanceof Uint8Array) {
    return { buffer: value, filename: "aivideotop.mp4", mimeType: "video/mp4" };
  }

  if (typeof value === "string" && (value.startsWith("http://") || value.startsWith("https://") || value.startsWith("/"))) {
    const r = await fetch(absoluteFileUrl(value));
    if (!r.ok) throw new Error(`Failed to fetch generated media: ${r.status}`);
    return {
      buffer: new Uint8Array(await r.arrayBuffer()),
      filename: value.endsWith(".mp4") ? "aivideotop.mp4" : "aivideotop.bin",
      mimeType: r.headers.get("content-type") ?? (value.endsWith(".mp4") ? "video/mp4" : undefined)
    };
  }

  if (!isFileLike(value)) return null;
  const url = value.url ?? value.path;
  if (!url) return null;

  const r = await fetch(absoluteFileUrl(url));
  if (!r.ok) throw new Error(`Failed to fetch generated media: ${r.status}`);

  return {
    buffer: new Uint8Array(await r.arrayBuffer()),
    filename: value.orig_name ?? value.name ?? "aivideotop.mp4",
    mimeType: value.mime_type ?? r.headers.get("content-type") ?? "video/mp4"
  };
}

async function extractMedia(data: unknown): Promise<{ buffer: Uint8Array; filename: string; mimeType?: string }[]> {
  const result: { buffer: Uint8Array; filename: string; mimeType?: string }[] = [];
  if (Array.isArray(data)) {
    for (const item of data) result.push(...await extractMedia(item));
    return result;
  }

  const direct = await toBuffer(data);
  if (direct) return [direct];

  if (data && typeof data === "object") {
    for (const value of Object.values(data as Record<string, unknown>)) {
      result.push(...await extractMedia(value));
    }
  }
  return result;
}

export class HuggingFaceProvider implements VideoProvider {
  private clientPromise: ReturnType<typeof Client.connect>;

  constructor() {
    const token = process.env.HF_TOKEN?.trim();
    this.clientPromise = Client.connect(SPACE_ID, token ? { token } : undefined);
  }

  async diagnose() {
    const client = await this.clientPromise;
    const info = await client.view_api() as ApiInfo;
    return Object.entries(info.named_endpoints ?? {}).map(([name, endpoint]) => ({
      name,
      parameters: endpoint.parameters?.length ?? 0
    }));
  }

  async generateVideo(input: VideoRequest): Promise<GenerationResult> {
    const client = await this.clientPromise;
    console.log(`[hf] generating final MP4 ${SPACE_ID}${ENDPOINT}`);

    const result = await client.predict(ENDPOINT, [input.prompt, -1, 15]) as { data?: unknown };
    const files = await extractMedia(result?.data);

    if (!files.length) {
      console.error("[hf] final endpoint returned:", JSON.stringify(result?.data));
      throw new Error("Hugging Face Self-Forcing returned no final video file");
    }

    const video = files.find(file =>
      file.mimeType?.toLowerCase().includes("video") ||
      file.filename.toLowerCase().endsWith(".mp4")
    ) ?? files[0];

    console.log(`[hf] final MP4 received: ${video.filename} (${video.buffer.byteLength} bytes)`);

    return {
      status: "completed",
      buffer: video.buffer,
      filename: "aivideotop.mp4",
      mimeType: "video/mp4",
      message: "Generated by Wan 2.1 Self-Forcing on Hugging Face ZeroGPU"
    };
  }
}
